Check whether the "checks" actually work (#19)
* [skip ci] imgaug.imgaug.quokka_square is deprecated.

* [skip ci] bugfix: Parameter cval is outside of the expected value range

* add cached downloader; switched from depreciated function

* switch depreciated function

* Verified checks/check_cartoon.py

* Verified checks/check_color_temperature.py

* Verified checks/check_fast_snowy_landscape.py

* rf: Changed depreciated data loading

* rf: Changed depreciated data loading

* fix: Replace non-working format string.

* fix: seed value locations have changed

* rf: Changed depreciated data loading

* add cached downloader

* doc: modify changelog

* rf: Changed depreciated data loading

* rf: downloader is recognized without PATH hacks

* add cached downloader

* rf: Changed depreciated data loading

* rf: Changed depreciated data loading

* rf: Changed depreciated data loading

* save todos

* tests: Added failing tests for set random_state

* changed: Handling of random_state in RandAugment

* add cached downloader

* fix: Ignore Resize augmentation to keep shape consistent

* [skip ci] tests: Added test for views in _multiply_elementwise_to_uint8_

* [skip ci] doc

* [skip ci] add changelog entry on multiply fix

* fix

* comment non working dtypes and processing steps
* cv2.flip does not support arrays of dtype bool or uint32

* fix: 'Layout of the output array dst is incompatible with cv::Ma'

* fix: Fortran layput is not supported for destination arrays

* fix: Error: 'numpy.ndarray' object has no attribute 'get'

* [skip ci] doc: Changes in `check_flip_performance.py`

* [skip ci] fix: Move local functions outside of main definition.

* [skip ci] doc: Add pull request link